done
jonasss312/HangmanTDD pull request #12
Opened 2022-02-03 14:17 UTC by jonasss312

2022-02-03 14:50 UTC, martynas-openg commented on Backend/src/usecase/implementation/GameCreator.ts
> +        // sitas usecase galetu matyt domain/Game ?
usecase gali matyti ir boundary, ir domain

2022-02-03 14:52 UTC, martynas-openg commented on Backend/src/usecase/implementation/GameCreator.ts
> +export class GameCreator implements GameCreatorInterface {
Usecas pavadinimams duok veiksmažodius, pvz. CreateGameUseCase
interface suffix daryk UseCase, o implementacijos suffix Interactor
tai dažniausiai bus ...Interactor implements {SomeAction}UseCase (vienas interaktorius gali implementinti kelis use case).
Šiuo atveju gali būti CreateGameInteractor implements CreateGameUseCase

2022-02-03 14:55 UTC, martynas-openg commented on Backend/src/usecase/implementation/GameCreator.test.ts
> +const wordGenerator: WordsFromFile = new WordsFromFile(testFileName);
kas yra už layerio (šiuo atveju usecase) ribų (šiuo atveju gateway) tuos dalykus reikės užsimockinti, o ne kurti tiesiogiai.
Kaip pvz. tau nereiktų kurti duombazės gateway, kad galėtum patestuoti interaktorių. Užtenka užsimockinti gateway interface metodus, kad tau grąžintų kažkokį rezultatą

2022-02-03 14:56 UTC, martynas-openg commented on Backend/src/domain/Game.ts
> +            else
šito else nereikia, tau ir taip pakvies tą this.isWhiteSpace(letter) ? ' ' : '#', nes pirmo ifo vidus turi returną

2022-02-03 14:57 UTC, martynas-openg commented on Backend/src/domain/Game.test.ts
> +        const guessedAllWordLetters =
kam tau guessedAllWordLetters, jeigu niekur nenaudoji?

2022-02-04 06:17 UTC, DovydasSp commented on Backend/src/usecase/api/GameCreationInterface.ts
> +export default interface GameCreatorInterface {
useCase'ų interface vadinam `somethingSomethingUseCase`, o implementacijas `somethingSomethingInteractor`

2022-02-04 06:19 UTC, DovydasSp commented on Backend/src/usecase/implementation/GameD2BConverter.ts
> +export class GameD2BConverter {
Nematau testo šitam konverteriui

2022-02-04 06:20 UTC, DovydasSp commented on Backend/src/usecase/implementation/GameCreator.ts
> +export class GameCreator implements GameCreatorInterface {
^ Šitas Marčio komentaras tikrai neresolved, nebent dar neišpushinai

2022-02-04 06:20 UTC, DovydasSp commented on Backend/src/domain/Game.ts
> +    private inGuessedLettersIsThisLetter(letter: string) {
kažkoks weird name. Pabandyk sugalvot kažką aiškiau

2022-02-04 08:14 UTC, DovydasSp commented on Backend/src/usecase/implementation/GameCreator.ts
> +import { BoundaryGame } from '../model/BoundaryGame';
File name

2022-02-04 09:00 UTC, DovydasSp commented on Backend/src/gateway/api/WordsGateway.ts
> +export default interface GamesGatewayWordsGateway {
name

2022-02-04 09:13 UTC, DovydasSp commented on Backend/src/usecase/implementation/GameD2BConverter.ts
> +export class GameD2BConverter {
Kitam PR padarė

2022-02-04 09:29 UTC, martynas-openg commented on Backend/src/usecase/implementation/GameCreator.test.ts
> +        const isGameBoundary = createdGame instanceof BoundaryGame;
kam šitas?

2022-02-04 09:30 UTC, DovydasSp commented on Backend/src/usecase/implementation/CreateGameInteractor.test.ts
> +    function assertCreatedGameBoundary(game: BoundaryGame, id:number, word: string){
assertInteractorOutput

2022-02-04 09:30 UTC, martynas-openg commented on Backend/src/usecase/implementation/GameCreator.test.ts
> +        expect(WORDS_GW.loadWord).toHaveBeenCalled;
čia šitas tikrai veikia? metodo nekvieti

2022-02-04 09:31 UTC, DovydasSp commented on Backend/src/usecase/implementation/CreateGameInteractor.test.ts
> +    function assertCreatedGameForGateway(game: Game, id:number, word: string){
assertGameGatewayAddGameParam

2022-02-04 09:32 UTC, DovydasSp commented on Backend/src/usecase/implementation/CreateGameInteractor.ts
> +        return new GameD2BConverter().convert(newGame);
Konverterį reiktų pasiduoti per konstruktorių iš konfigūracijos. Tada testuose gali arba real implementation paduoti, arba jei nereikia tikrinti kažkokių fieldų tai mock'ą

2022-02-04 09:32 UTC, jonasss312 commented on Backend/src/usecase/implementation/GameD2BConverter.ts
> +export class GameD2BConverter {
padariau kitame PR

2022-02-04 09:42 UTC, jonasss312 commented on Backend/src/usecase/implementation/GameCreator.test.ts
> +        expect(WORDS_GW.loadWord).toHaveBeenCalled;
ar reikia WORDS_GW.loadWord irgi prideti skliaustelius? pvz. : WORDS_GW.loadWord()

2022-02-04 11:34 UTC, DovydasSp commented on Backend/package.json
> +    "test": "jest --coverage",
nuimk čia tą --coverage

2022-02-04 12:37 UTC, martynas-openg requested changes
įdėk node_modules į .gitignore ir parevertink commitą kur sukomitinai juos

2022-02-04 12:38 UTC, martynas-openg commented on Backend/src/usecase/implementation/CreateGameInteractor.ts
> +            new Game(
jeigu skirstai taip į kiekvieną eilutę tai grąžiau bus jeigu new iškelsi į metodą

2022-02-04 12:41 UTC, DovydasSp approved these changes

2022-02-04 13:04 UTC, DovydasSp approved these changes

2022-02-04 13:06 UTC, martynas-openg approved these changes

2022-02-04 13:35 UTC, merged